packages:
  - software/annotator
  - software/annotation2filters
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.1
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.7.3
  '@platforma-sdk/model': 1.48.14
  '@platforma-sdk/ui-vue': 1.48.14
  '@platforma-sdk/tengo-builder': 2.4.5
  '@platforma-sdk/package-builder': 3.10.7
  '@platforma-sdk/block-tools': 2.6.27
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.48.18
  '@milaboratories/helpers': 1.12.1

  '@platforma-open/milaboratories.runenv-python-3': 1.7.5
  '@platforma-open/milaboratories.software-ptransform': 1.6.6
  '@platforma-open/milaboratories.software-binary-collection.software-7zip': 1.2.3

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  'canonicalize': ~2.1.0
  'lodash': ^4.17.17
  '@types/lodash': ^4.17.20
  'zod': ~3.23.8
  'utility-types': ^3.11.0
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.16
  'eslint': ^9.25.1
  '@vueuse/core': ^13.5.0
  'ag-grid-enterprise': &ag-grid ~33.3.2
  'ag-grid-vue3': *ag-grid
  '@changesets/cli': ^2.29.8
  'sass-embedded': ^1.89.2

  # other blocks used in tests
  '@platforma-open/milaboratories.samples-and-data': ^1.12.3
  '@platforma-open/milaboratories.samples-and-data.model': ^2.4.1
  '@platforma-open/milaboratories.mixcr-clonotyping-2': ^2.12.10
  '@platforma-open/milaboratories.mixcr-clonotyping-2.model': ^1.17.2
  '@platforma-open/milaboratories.clonotype-clustering': ^2.5.13
  '@platforma-open/milaboratories.clonotype-clustering.model': ^2.13.6
